api:
  http:
    addr: 0.0.0.0
    port: 7601
dms:
  data:
    database:
      username: root
      password: pass
      host: 127.0.0.1
      port: 3306
      database: dms
      debug: true
node:
  nodeno: 1
cloudbeaver:
  enable_https: false
  host: 127.0.0.1
  port: 8978
  admin_user: admin
  admin_password: admin

