dms:
  id: 1
  api:
    addr: 0.0.0.0
    port: 10000
  service:
    database:
      username: root
      password: 123
      host: 127.0.0.1
      port: 3306
      database: dms
      auto_migrate: true
    log:
      level: INFO
      path: logs
      max_size_mb: 100
      max_backup_number: 10
  cloudbeaver:
    enable_https: false
    host: 127.0.0.1
    port: 8978
    admin_user: administrator
    admin_password: 123456
  secret_key:
  server_id:
  enable_cluster_mode: false
  report_host: # the host name or IP address of the cluster node
